apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: ghcr.io/adrn1201/crm-backend:v1.0.4
          ports:
            - containerPort: 8000
          env:
            - name: MONGODB_URI
              value: mongodb://mongo:27017/mydatabase
      imagePullSecrets:
        - name: ghcr-secret