apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.backend.appName }}
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.backend.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.backend.appName }}
    spec:
      containers:
        - name: backend
          image: {{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}
          ports:
            - containerPort: {{ .Values.backend.containerPort }}
          env:
            - name: MONGODB_URI
              value: "{{ .Values.backend.env.MONGODB_URI }}"
      imagePullSecrets:
        - name: {{ .Values.backend.image.pullSecret }}
