apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crm-application
  namespace: argocd 
spec:
  project: default

  source:
    repoURL: https://github.com/adrn1201/crm-gitops.git
    targetRevision: HEAD
    path: crm-chart               
    helm:
      valueFiles:
        - values.yaml           
  destination:
    server: https://kubernetes.default.svc
    namespace: default           

  syncPolicy:
    automated:
      prune: true                 
      selfHeal: true              
    syncOptions:
      - CreateNamespace=true     
